### ISSUE TITLE
illegal string offset 

### ISSUE THREAD

**Issue by vjchandrika** [wpsf/wpsf-dev#1]
once finished configuration wpsf give issues like this 
## Warning: Illegal string offset 'errors' in D:\xampp\htdocs\projects\clarup\clarup-wp\wp-content\themes\clarup\inc\wpsf-framework\classes\settings.php on line 368
this issue was occured only at first time loaded 
![Uploading image.png…]()

**Comment by varunsridharan** [comment]
@vjchandrika issue fixed in latest commit.
