### ISSUE TITLE
Nested Group

### ISSUE THREAD

**Issue by emsohel** [wpsf/wpsf-dev#5]
Nested group element value is not saved properly and at first click first accordion child group returns more then one accordion which is equal to parent accordion.

**Comment by varunsridharan** [comment]
@emsohel thanks for reporting. and i am really happy to announce that i am working on a brand new framework which will be released in 5 days max.
i no longer going to support this framework.

**Comment by varunsridharan** [comment]
@emsohel i would like to inform you that i brand new Settings framework is now in public beta 
http://github.com/wponion/wponion/

Please do have a look @ it.
