### ISSUE TITLE
Multiple instance and visual composer support 

### ISSUE THREAD

**Issue by webangon** [wpsf/wpsf-dev#6]
Hi good fork !! 
Does it support multiple instance and visual composer ?

**Comment by varunsridharan** [comment]
@webangon yea it dose. but we no longer going to support it. since we moved from wpsf to wponion. where VC Support will be added very soon.

**Comment by webangon** [comment]
Thank you for quick reply . I tried wponion but you are missing files. Look forward and great job !!!
![capture](https://user-images.githubusercontent.com/7946657/48055069-ec649380-e1d8-11e8-8d36-f38a290a2ba9.PNG)

**Comment by varunsridharan** [comment]
@webangon thanks for tryingout WPOnion.
i would like to know from where you have downloaded the WPOnion?
Also if possible please do connect with me on skype 
so i that i can help on this
Skype : varunsridharan23@gmail.com
