### ISSUE TITLE
How to enable theme light color

### ISSUE THREAD

**Issue by groupunknown** [wpsf/wpsf-dev#7]
How to enable theme light color, there is this option?

**Comment by varunsridharan** [comment]
@groupunknown we no longer support WPSF instead we already released a near stable beta version of a brand new framework which is called as WPOnion you can download it from

http://github.com/wponion/wponion

**Comment by groupunknown** [comment]
seems to be promising, but the documentation is confusing, I could not install :(, but thanks for responding

**Comment by varunsridharan** [comment]
@groupunknown actually WPOnion is more like WPSF but its more powerfull and has a lot of options

## So what is WPOnion , exactly?

WPOnion is a simple yet powerful framework that helps developers build custom meta boxes and custom fields in WordPress fast and easily.

The framework lets you define custom meta boxes and custom fields via arrays and handles everything behind the scene automatically. It has a wide range of field types, field settings and supports not only post meta but also term meta, user meta, comment meta, settings pages and custom tables.

WPOnion packed with **12 Modules & 42 Field Types.**

## Contribution
Like WPOnion Framework, this documentation is open sourced on Github & GitBooks. The website’s content is written in Markdown.

If you find anything incorrect in the documentation or out-dated, please help us fix it.

In case you come across anything along the way that we haven’t covered, or if you know of a tip you think others would find handy, please file an issue and we’ll see about including it in this guide.
Features
Released

---
Github Link : http://github.com/wponion/

Demo Link : http://wponion.com/demo

Demo Link : https://wponion.gitbook.io/docs/

**Comment by groupunknown** [comment]
thank you
